FIND_PATH(CPPREST_INCLUDE_DIR cpprest/version.h pplx/pplx.h)

FIND_LIBRARY(CPPREST_LIBRARIES NAMES cpprest)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(CPPREST REQUIRED_VARS CPPREST_LIBRARIES CPPREST_INCLUDE_DIR)

# show the CPPREST_INCLUDE_DIR and CPPREST_LIBRARIES variables only in the advanced view
MARK_AS_ADVANCED(CPPREST_INCLUDE_DIR CPPREST_LIBRARIES)
